set nocompatible
filetype off

set rtp+=~/.vim/vundle.git/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'thinca/vim-quickrun'
Bundle 'scrooloose/nerdtree'
Bundle 'Shougo/vimshell'
Bundle 'Shougo/vimproc'
Bundle 'Source-Explorer-srcexpl.vim'
Bundle 'trinity.vim'
"Bundle 'taglist.vim'

filetype plugin indent on

colorscheme darkblue
"colorscheme default

set t_RV=
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,iso-2022-jp,euc-jp,cp932
set fileformats=unix,dos,mac
set ambiwidth=double

" インデント
set smartindent
set autoindent
set cindent

" タブの設定
set tabstop=4 shiftwidth=4
set expandtab
set shiftround

" 表示の設定
set list
set listchars=tab:>-,extends:<,trail:-,eol:<

set number
set showmatch

" 検索の設定
set ignorecase
set smartcase

" ステータス行の表示
set laststatus=2
set statusline+=[ENCODE=%{&fileencoding}]
set statusline+=[FORMAT=%{&ff}]
set statusline+=[TYPE=%Y]
set statusline+=[LEN=%L]
set statusline+=[POS=%04l,%04v]
set statusline+=[%p%%]
set statusline+=[%F]

set cmdheight=2
set showcmd
set title

"ウィンドウタブ
imap ,t :tabnew

autocmd FileType yaml set sw=2 ts=2
autocmd FileType html set sw=2 ts=2
autocmd FileType ruby set sw=2 ts=2
autocmd BufNewFile,BufRead *.psgi set filetype=perl
autocmd BufNewFile,BufRead *.ru set filetype=ruby

syntax enable
let perl_no_extended_vars=1

