# vim:ft=zsh:
# .zprofile

LOGIN_SHELL=1

stty -ixon
umask 022

export PAGER="lv -c"

if [ -f ${HOME}/.zsh/workprofile ]
then
    source ${HOME}/.zsh/workprofile
else
    source ${HOME}/.zsh/devprofile
fi

