# vim:ft=zsh:

path=(
    {,${HOME}}{/usr/{/local,},}/{,s}bin
)

limit coredumpsize 0
if [ `uname` != 'Darwin' ]
then
    eval `dircolors $HOME/etc/dircolors`
fi


# シェルスクリプトを実行するときいろいろ困るので
source "${HOME}/.zsh/devenv"
