config:
	ln -fs `pwd`/home/.zshrc      ${HOME}/
	ln -fs `pwd`/home/.zshdevrc   ${HOME}/
	ln -fs `pwd`/home/.zprofile   ${HOME}/
	ln -fs `pwd`/home/.vimrc      ${HOME}/
	ln -fs `pwd`/home/.tscreenrc  ${HOME}/
	ln -fs `pwd`/home/.screenrc   ${HOME}/
	ln -fs `pwd`/home/.gitconfig  ${HOME}/
	ln -fs `pwd`/home/etc         ${HOME}/
	mkdir -p ${HOME}/opt
	ln -fs `pwd`/home/bin         ${HOME}/opt/

