dev:
	ln -fs `pwd`/home/zshrc      ${HOME}/.zshrc
	mkdir -p ${HOME}/.zsh
	ln -fsn `pwd`/home/zsh/devrc ${HOME}/.zsh/devrc
	ln -fs `pwd`/home/zprofile   ${HOME}/.zprofile
	ln -fs `pwd`/home/vimrc      ${HOME}/.vimrc
	ln -fsn `pwd`/home/vim       ${HOME}/.vim
	ln -fs `pwd`/home/tscreenrc  ${HOME}/.tscreenrc
	ln -fs `pwd`/home/screenrc   ${HOME}/.screenrc
	ln -fsn `pwd`/home/etc       ${HOME}/etc
	mkdir -p ${HOME}/opt
	ln -fs `pwd`/home/bin        ${HOME}/opt/bin

git:
	ln -fs `pwd`/home/gitconfig  ${HOME}/.gitconfig
